# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0002_remove_mentor_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='tag',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
