# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0003_mentor_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
